config/routes.rb
Rails.application.routes.draw do
  get 'rsvp/new'

  root             'static_pages#home'
  get 'details'   => 'static_pages#details'
  get 'contact' => 'static_pages#contact'
  get 'register'=> 'static_pages#register'
  get 'accomodation' => 'static_pages#accomodation'
  get 'photos' => 'static_pages#photos'
  get 'rsvps' => 'rsvp#new'
  post 'rsvps' => 'rsvp#create'
  get 'created' => 'rsvp#created'
  resources :rsvp
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  @FOODS = ['prime rib', 'chicken', 'vegetarian']
  validates :name, presence: true
  validates :FoodPreference, presence: true,
                            :inclusion => @FOODS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "hey baby!"
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def new
    @rsvp = Rsvp.new
  end
  
  def show
    @rsvp = Rsvp.find(params[:id])
  end
  
  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      flash[:success] = "Thanks for RSVPing, it's been saved!"
      redirect_to 
    else 
      render 'new'
    end
  end
  
  def created
    
  end
  
  private
    def rsvp_params
      params.require(:rsvp).permit(:name,:email,:attending,:FoodPreference,:additionalInfo)
    end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @pageClass = 'homepage'
  end
  
  def details
    @pageClass = 'details'
    @partialViewClass = 'container greyBackground'
  end
  
  def contact
  end
  
  def register
  end
  
  def accomodation
  end
  
  def photos
  end
  
  def rsvp
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Andrew and Caitie wedding"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Thanks to the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top center">
  <div class="container">
    <!--<%= link_to "Andrew and Caitie", root_path, id: "logo" %>-->
    <nav>
      <ul class="nav navbar-inner">
        <li><%= link_to "HOME",   root_path %></li>
        <li><%= link_to "DETAILS",   details_path %></li>
        <li><%= link_to "REGISTER",   register_path %></li>
        <li><%= link_to "RSVP",   rsvps_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="<%= @pageClass %>">
  <%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/rsvp/created.html.erb
Thanks!

app/views/rsvp/new.html.erb
<% provide(:title, 'RSVP') %>

  <div class="col-md-12 bigBottom">
    <%= image_tag("rsvpheader.jpg") %>
  </div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rsvp) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name, :class => "boldLabel" %>
      <%= f.text_field :name, :class => "form-control" %>
      
      <%= f.label :email, :class => "boldLabel" %>
      <%= f.email_field :email, :class => "form-control" %>
      
      <%= f.label "Do you plan on attending?", :class => "boldLabel" %>
      <br />
      
      &nbsp;&nbsp;&nbsp;<%= f.radio_button :attending, true, :checked => true %>
      <%= f.label :attending, :value => 'Yes' %>
      <br />
      
      &nbsp;&nbsp;&nbsp;<%= f.radio_button :attending, false %>
      <%= f.label :attending, :value => 'No' %>
      <br />
      <br />
      
      <%= f.label "Meal Selection", :class => "boldLabel" %>
      
      <% [ 'chicken', 'prime rib', 'vegetarian' ].each do |foodPreference| %>
        <br>&nbsp;&nbsp;&nbsp;<%= f.radio_button :FoodPreference, foodPreference %>
        <%= label_tag "rsvp_FoodPreference_#{foodPreference}", foodPreference.humanize %>
      <% end %>
      <br />
      <br />
      
      <%= f.label "Additional Information", :class => "boldLabel" %>
      <%= f.text_area :additionalInfo, :class => "form-control" %>
      
      <%= f.submit "Send RSVP", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rsvp/show.html.erb
<%= @rsvp.name %>,<%= @rsvp.email %>,<%= @rsvp.attending %>,<%= @rsvp.additionalInfo %>

app/views/shared/_error_messages.html.erb
<% if @rsvp.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@rsvp.errors.count, "error") %>.
    </div>
    <ul>
    <% @rsvp.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Created by Andrew Alkema
</p>

app/views/static_pages/details.html.erb
<% provide(:title, "About") %>
<div class="container">
    
  <div class="col-md-12 bigBottom">
    <%= image_tag("detailsHeader.jpg") %>
  </div>
  
    <div class="col-md-6">
      <div class="detailsGrayBox">
        <p style="font-size:150%"><b>Ceremony Details</b></p>
        <p><b>Location:</b> Stirling Avenue Mennonite Church, Kitchener ON</p>
        <p><b>Date and Time:</b> Saturday October 17, 2015, 3:00 PM</p>
        <div style="text-align:center">
          <iframe width="467" height="350" frameborder="0" class="mapFrame" src="https://www.google.com/maps/embed/v1/place?q=Stirling%20Ave%20Mennonite%20Church%2C%20Stirling%20Avenue%20North%2C%20Kitchener%2C%20ON%2C%20Canada&key=AIzaSyA2JLlp_W08DDWFtHzqkTEJNXfu-aYKQS8" allowfullscreen></iframe>
        </div>
      </div>
      <br /><br />
    </div>  
    
    <div class="col-md-6" >
      <div class="detailsGrayBox">
        <p style="font-size:150%"><b>Reception Details</b></p>
        <p><b>Location:</b> New Dundee Country Club, Wilmot ON</p>
        <p><b>Date and Time:</b> Saturday October 17, 2015, 5:30 PM</p>
        <div style="text-align:center">
          <iframe width="467" height="350" frameborder="0" class="mapFrame" src="https://www.google.com/maps/embed/v1/place?q=Dundee%20Country%20Club%2C%20Wilmot%2C%20ON%2C%20Canada&key=AIzaSyA2JLlp_W08DDWFtHzqkTEJNXfu-aYKQS8" allowfullscreen></iframe>
        </div>
      </div>
        <br /><br />
    </div>  
  
</div>

app/views/static_pages/home.html.erb
<div class="center">
  <!--<%= image_tag("headerweb.jpg") %>-->
</div>
<div class="filledDiv absoluteCenter300" style="bottom: 25px">
  <h1>Andrew & Caitie</h1>
  <h2>October 17, 2015</h2>
</div>

app/views/static_pages/register.html.erb
<div class="container">
  
  <div class="col-md-12 bigBottom">
    <%= image_tag("registerHeader.jpg") %>
  </div>
  
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <p>
      If you wish to contribute gifts to aid us in beginning our home together, please use these sites for suggestions 
      of things that we would find useful. Just know that your presence is a gift big enough for us, so don't feel 
      obliged to purchase anything to come to the party.
    </p>
    <br /><br />
    <p style="font-size:150%"><b>Hudson's Bay Company</b></p>
    <p>
      <a href="http://giftregistry.hbc.com/grworks/prj/generic_online/jsp/common/grbookmark.jsp?retailerid=4&cc=400126231041&languageid=0" >Link to Registry</a>
    </p>
    
    <br /><br />
    <p style="font-size:150%"><b>Adventure Guide</b></p>
    <p>Adventure Guide doesn't have a registry option, so any gift cards will help us begin our core camping collection - a tent, a camp stove and other gear.</p>
    <p>
      <a href="http://advguide.com/" >Link to store website</a>
    </p>
    
  </div>

  
</div>